export const FLIGHTS = [
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },




    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },
    


    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },



    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },



{   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },




{   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },




{   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AI-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'BANGALORE',
        destination: 'DELHI',
        flightCode: 'AA-101',
        originCode: 'BLR',
        destinationCode: 'DEL',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AI-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'BANGALORE',
        destination: 'JAIPUR',
        flightCode: 'AA-102',
        originCode: 'BLR',
        destinationCode: 'JAI',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AI-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'BANGALORE',
        destination: 'PUNE',
        flightCode: 'AA-103',
        originCode: 'BLR',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },


















{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },



    
{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },


    
{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },



{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },

    
{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },

    
{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },

    
{   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AI-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'DELHI',
        destination: 'BANGALORE',
        flightCode: 'AA-201',
        originCode: 'DEL',
        destinationCode: 'BLR',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 1500
    },{   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AI-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'DELHI',
        destination: 'JAIPUR',
        flightCode: 'AA-202',
        originCode: 'DEL',
        destinationCode: 'JAI',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 2500
    },{   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AI-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'DELHI',
        destination: 'PUNE',
        flightCode: 'AA-203',
        originCode: 'DEL',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 PM',
        arriveTime: '10.00 PM',
        price: 3500
    },

















    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-16',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },

    

    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-17',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },
    



    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-18',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },




    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-19',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },




    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-20',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },




    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-21',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },




    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AI-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1000
    },
    {   origin: 'JAIPUR',
        destination: 'BANGALORE',
        flightCode: 'AA-301',
        originCode: 'JAI',
        destinationCode: 'BLR',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 1500
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AI-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2000
    },
    {   origin: 'JAIPUR',
        destination: 'DELHI',
        flightCode: 'AA-302',
        originCode: 'JAI',
        destinationCode: 'DEL',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 2500
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AI-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3000
    },
    {   origin: 'JAIPUR',
        destination: 'PUNE',
        flightCode: 'AA-303',
        originCode: 'JAI',
        destinationCode: 'PNQ',
        departDate: '2018-04-22',
        departTime: '08.00 AM',
        arriveTime: '10.00 PM',
        price: 3500
    },


];